package frsf.isi.died.app.controller;

public enum TiposAcciones {
	ABM_LIBROS,ABM_VIDEOS, BUSQ_LIB, BUSQ_VID, AGREGAR_CONT, BUSCAR_CONT, AGREGAR_WISHLIST, VER_WISHLIST, VER_GRAFO, VER_GRAFO_CAMINOS, VER_PAGE_RANK, ACT_LIBRO, ACT_VIDEO, ELIM_LIBRO, ELIM_VIDEO
}
